### ISSUE TITLE
Implement Server

### ISSUE THREAD

**Issue by hunterjsb** [jcpage573/prisoners-dilemma#1]
## Issue
We need a server! So that people can write their own clients and play over http.

## Suggested Endpoints
@jcpage573 thoughts on endpoints?

**Comment by jcpage573** [comment]
A /{game_id} and we do query params for question #'s and answers?

**Comment by jcpage573** [comment]
A /{game_id} and we do query params for question #'s and answers?

**Comment by hunterjsb** [comment]
so maybe POST a new game GET game details, PATCH new moves?

**Comment by jcpage573** [comment]
What about a query param like ?question=1 to store the state of the game then a post to add an answer

**Comment by hunterjsb** [comment]
I think posting new moves makes sense, dunno if we need to keep state in the query params since youll only ever be posting an answer to the latest question right?

**Comment by hunterjsb** [comment]
- [ ] #9 
- [ ] Store API keys and usernames
- [ ] Store match history
- [ ] Matchmaking
